### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jingsiyi** [lwei02/SichuanUniv_GetCourseBook#1]
**Describe the bug**

SichuanUniv_GetCourseBook\getBooks.py", line 137, in <module>
    stu_api_key = stu_api_script.split('        url: "/student/courseSelect/thisSemesterCurriculum/')[1].split('/ajaxStudentSchedule/past/callback",')[0]
 
                 
IndexError: list index out of range

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lwei02** [comment]
教务系统更新之后接口有变化，另外教师系统也没法用SSO登录进去了，现在这个程序是失效状态，目前暂时没有替代解决方案。

**Comment by jingsiyi** [comment]
好的，谢谢
